### ISSUE TITLE
Comments on Nim Impl

### ISSUE THREAD

**Issue by awr1** [shish/rosettaboy#115]
[I had been linked to this on the Nim forums](https://forum.nim-lang.org/t/9859) and I just wanted to say, first of all, sorry for your poor first impression of Nim. It can be a quirky language if you come in with certain expectations - trying finding the right documentation especially can lead to a lot of red herrings. I do recommend the [manual](https://nim-lang.org/docs/manual.html), which is a sort of official spec-but-not-really-a-spec that helps to clarify most of the root behavior and utilities of the language (alongside certain docs like the generated docs for [`std / macros`](https://nim-lang.org/docs/macros.html) which define the user-manipulable AST, [the experimental features doc](https://nim-lang.github.io/Nim/manual_experimental.html), etc.)

For context, I've been using Nim for approximately five years or so, and had been initially skeptical of it the first time I was introduced. It can be hard to figure out what is actually "attractive" about Nim, but I would say the type system ergonomics and the multi-tiered macro system are the primary selling points. I like to consider Nim a sort of "Lisp for the modern age" (even though it doesn't seem to walk or talk like Lisp at first glance) with a broader appeal and reconsidered semantics. I took the time to read your comments, so I'd like to push you a little in the right direction.

RE: Argument parsing, the standard library command line parser (parseopt) is kind of barebones and does not really take advantage of the language that well (for instance it has no help generation). I think you had an issue in figuring out how to actually feed arguments from the command line to the parser, however the default behavior (the empty string) automatically picks them out. I would have done something like this if I were just using the standard library parser:

```nim
import std / [os, parseopt]

type
  ArgFlags* = enum 
    Headless, Silent, DebugCPU, DebugAPU, DebugGPU, DebugRAM, Turbo
  Args* = ref object
    rom*: string
    frames*, profile*: int
    flags*: set[ArgFlags]

proc parseArgs*(): Args =
  for kind, key, value in initOptParser.getOpt:
    case kind
    of cmdShortOption, cmdLongOption:
      if value == "":
        result.flags.incl case key
        of "H", "headless":  {Headless}
        of "S", "silent":    {Silent}
        of "c", "debug-cpu": {DebugCPU}
        of "g", "debug-gpu": {DebugAPU} 
        of "r", "debug-ram": {DebugRAM} 
        of "t", "turbo":     {Turbo}
        else:                {}
      else:
        case key
        of "f", "frames":  result.frames  = parseInt(value)
        of "p", "profile": result.profile = parseInt(profile)
    of cmdArgument:
      result.rom = key
    of cmdEnd:
      break
```

For some context, Nim instantiates a hidden "result" convenience variable that is automatically returned if no explicit returns are made. `set[T]` is also a bitset-like type useful for compacting what would otherwise be a bunch of boolean fields, from which one can test, e.g. `if Headless in args.flags: ...`

In regards to `const`, Nim has three primary degrees of variable constancy. They are `var`, which refers to a mutable variable, `let`, which is a more standard "runtime" (if not compiletime-foldable) constant, and also `const`, which is like `let` but it enforces the compiletime constraint.

Nim's `bitops` library contains a lot of extraction methods (like `bitsliced()`) that I would personally opt for if I were developing an opcode interpreter in lieu of doing manual shifts. In spite of this, Nim offers very broad operator overloading abilities such that is quite possible to reintroduce C-like bit manipulation syntax. You can even constrain the scope of your overloads if you want.

```nim
import std / bitops

template cBitops(body: untyped): untyped =
  block:
    template `&`(a, b:  SomeInteger): SomeInteger = bitand(a, b)
    template `|`(a, b:  SomeInteger): SomeInteger = bitor(a, b)
    template `<<`(a, b: SomeInteger): SomeInteger = a shl b
    template `>>`(a, b: SomeInteger): SomeInteger = a shr b
    body

let x = cBitops (13092 | 4124) & (2 << 3) # 16
```

Nimpretty is broken and has a few bugs where it betrays semantic equivalence, I do agree that this is not a good look but I would not really recommend using it.

Nim deep-copies by default, including sequence types (to make no mention of [ARC,](https://nim-lang.org/docs/destructors.html) which challenges these semantics significantly) unless the object in question is a `ref`. You should consider using a `ref object` to avoid a deep-copy. 

The Apple Silicon issue with choosenim has annoyed me for some time, but you can use choosenim with a native ARM build of the compiler suite if you have a local repo built if it helps.

I hope this sheds some lights on the issues you've been having. Neat polyglot project in any case! In spite of the Nim forum not working for you, you can try [IRC/Gitter](https://gitter.im/nim-lang/Nim), which is usually pretty active.

**Comment by inv2004** [comment]
To link it somewhere, please find some fixed for Nim implementation: https://github.com/shish/rosettaboy/pull/117

**Comment by shish** [comment]
Thank you for all the tips :) I'mma leave this issue open for bit as a reminder for myself to go back and learn more

**Comment by inv2004** [comment]
@shish would you like to update readme table tested on your hardware?

Thank you,

**Comment by shish** [comment]
The nim (and mypyc) versions have stopped building for me, I'm getting weird linker errors that I'm pretty sure are due to my laptop having a weird mix of LLVM versions installed, so I need to fix that first ^^;;

**Comment by shish** [comment]
Managed to get everything to build at the same time, and nim is now on top :O
