### ISSUE TITLE
[go] use normal CLI flags

### ISSUE THREAD

**Issue by shish** [shish/rosettaboy#163]
Every other language has `-x` for short flags and `--xxx` for long flags -- go uses `-xxx` for long flags and doesn't support (?) short flags. Is there a third-party flags library which acts more normal?

**Comment by RISHIKESHk07** [comment]
hey @shish  i am a novice in go, I found this project https://github.com/spf13/pflag
not sure it will help

**Comment by shish** [comment]
That does look very useful - if it's as simple as it looks this might be a one-liner :O
