### ISSUE TITLE
In php github workflow not use sdl2 lib binding

### ISSUE THREAD

**Issue by kocoten1992** [shish/rosettaboy#30]
Hi, I just saw your comment on top of ycombinator (congrats!), checking out this repo I notice that in all github workflow we are using sdl2 lib binding, but in php github workflow I didn't see it being use (It is still actively maintained at https://github.com/Ponup/php-sdl).

That may yield why php is roughly the same speed with python (it is faster in my experience).

I've never use SDL2 for php so I don't yet know how, creating this issue for tracking (as I might try SDL with php on weekend).

**Comment by shish** [comment]
That looks like it should work - hopefully it's as simple as deleting the empty stub functions in `_sdl.php` and installing the `sdl.so` extension and fingers crossed it all runs first time :)

**Comment by kocoten1992** [comment]
sadly, I don't think it work, I got segfault when try php-sdl lib

```
(No debugging symbols found in php)
(gdb) run src/main.php -S -H -p 1 -t opus5.gb
Starting program: /usr/bin/php src/main.php -S -H -p 1 -t opus5.gb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x0000555555850627 in zend_fetch_resource ()
```

**Comment by kocoten1992** [comment]
Here is short reproduction:

# rosettaboy.Dockerfile

```
FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y

RUN apt install software-properties-common -y

RUN add-apt-repository ppa:ondrej/php

RUN apt install php php-xml php-cgi php-pgsql php-swoole php-pear php-dev libsdl2-dev vim git wget gdb -y

RUN pecl install sdl-beta

RUN echo "extension=sdl.so" >> /etc/php/8.1/cli/php.ini

RUN git clone https://github.com/shish/rosettaboy

RUN cd /rosettaboy/php/ && wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb\?raw\=true -O opus5.gb
```

```
docker build -t rosettaboy-php -f rosettaboy.Dockerfile .
```

```
docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined rosettaboy-php /bin/bash
```

I'm out of wit atm, maybe escalate to php-sdl maintainer ?
