### ISSUE TITLE
Small typing mistake in `gpu.py` I think.

### ISSUE THREAD

**Issue by will-ca** [shish/rosettaboy#83]
IIRC I was thrown off a bit by this.

`palette` in `GPU.paint_tile()` and `GPU.paint_tile_line()` is typed to `SDL_Color`.

https://github.com/shish/rosettaboy/blob/177f282c7b0e10eb5df0e0597d966a7ccc8e9ab9/py/src/gpu.py#L365-L372

https://github.com/shish/rosettaboy/blob/177f282c7b0e10eb5df0e0597d966a7ccc8e9ab9/py/src/gpu.py#L388-L396

However, in all invocations, it's set to something like `self.bgp`, `self.obp1`, or `self.obp0`, which are actually `List[SDL_Color]`:

https://github.com/shish/rosettaboy/blob/177f282c7b0e10eb5df0e0597d966a7ccc8e9ab9/py/src/gpu.py#L325

https://github.com/shish/rosettaboy/blob/177f282c7b0e10eb5df0e0597d966a7ccc8e9ab9/py/src/gpu.py#L344-L353

https://github.com/shish/rosettaboy/blob/177f282c7b0e10eb5df0e0597d966a7ccc8e9ab9/py/src/gpu.py#L205-L228

**Comment by shish** [comment]
That is correct, and I have no idea why neither mypy nor pyre flag that as a problem o_O
